version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install
      - run: npm run build
workflows:
  node-build-test:
    jobs:
      - build
      - node/test