version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install
      - run: CI=true npm run build
workflows:
  node-build-test:
    jobs:
      - build
      - node/test